### ISSUE TITLE
create_stem_image_sparse radii as list

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#102]
create_stem_image_sparse only take a single inner_ and outer_radii. Can it take a list or tuple to craete multiple STEM images at once. Similar to create_stem_image

```python
>> stem_from_sparse = image.create_stem_image_sparse(frame_events, (0,200,), (200,288,))
TypeError: create_stem_images_sparse(): incompatible function arguments. The following argument types are supported:
    1. (arg0: List[List[int]], arg1: List[int], arg2: List[int], arg3: int, arg4: int, arg5: int, arg6: int, arg7: int, arg8: int, arg9: int) -> List[stempy._image._image_uint64]
    2. (arg0: stempy._image._electron_counted_data, arg1: List[int], arg2: List[int], arg3: int, arg4: int) -> List[stempy._image._image_uint64]
```

The error seems to imply that the function takes a list, however it does not work.

**Comment by cjh1** [comment]
@ercius Try `create_stem_images_sparse(...)`, note the `images`. We can also add logic to `create_stem_image_sparse(...)` to redirect to the right function if called with a list ...

**Comment by ercius** [comment]
Got it. Thanks!

**Comment by cjh1** [comment]
I think this is now resolved
