### ISSUE TITLE
width vs height vs x vs y vs...

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#106]
For non-square scans Im getting confused as to which order to put the scan values in.

We should think about how to unify the inputs and outputs to all functions in terms of which axis is desired when variables like height and width are used as well as variable names with x and y.

Personally, I prefer to use tuples for these kinds of inputs and outputs. For example, if you have a 4D array of shape `[scany,scanx,ky,kx]` it can be easier to have a function input like:
```python
def my_func(data, scan_x_y, frame_x_y):
    ''' arbitrary function
    Inputs
        data : ndarray
                The data to input
        scan_x_y: tuple, 2-element
                The scan size which corresponds to the first and second data axes
        frame_x_y: tuple, 2-element
                The size of each detector frame corresponding to the third and fourth axes
    '''
```
Thus, the tuple order matches the order in the data. This gets away from width/height and x/y where you might be confused as to which is which. Is the (x, y) order like humans are used to or (y,x) order which is more like C-Ordering. Does width == x and height == y? Or the other way around

**Comment by cjh1** [comment]
@ercius I agree this is an area of much confusion! Even writing this, I had to check the code! I think spending some time to clear this up is a good idea. Yes, currently x,y == width, height == columns, rows, if there is a more familiar convention we can switch to it?

**Comment by cjh1** [comment]
As part of this adding doc strings to function would also help.

**Comment by cryos** [comment]
Major thing would probably be more explicitly documenting. I would expect all pairs to be x, y and width, height. Using tuples seems like a reasonably approach, writing x = 10, y = 5 could help too, then you can be very explicit about them in Python at least.

**Comment by cjh1** [comment]
@cryos your right using named parameters is another option, which prevent getting things out of order. I was trying to look for prior art in the numpy world, I guess the most basic example is the construction of an n-d array, where the dimensions are passed as a tuple.

**Comment by cjh1** [comment]
Look like this is related #54 ( we have thought about this before :-) )

**Comment by ercius** [comment]
Haha. I guess that was a good idea even back then!

**Comment by cjh1** [comment]
Yep, I think we should go with the tuple approach.

**Comment by cjh1** [comment]
I want to make sure we get this right, so thought some diagrams might help clarify things (@ercius I think the x and y for the parameters are in fact reversed, they don't match the order in the data? ) If we are looking at a scan or frame the coordinate it looks like the following.

(0,0)                    x
    + ------------------------------------ >
    |
    |
y  |
    |
    |
   +
                          

And this should correspond to a 2 - d array in memory.

 [[..................................................],
  [..................................................],
  [..................................................],
                         ...
  [..................................................]
  [..................................................]]

So to access a position of x,y in the scan or frame in the array,  row = y and column = x

Does this match everyone's view?

**Comment by ercius** [comment]
@psavery That is a mistake. I see how that can be confusing.

@cjh1 Your plotting of the scan directions is correct. The origin is in the upper left and the x, horizontal direction is the "fast scan" direction for a STEM image. The beam looks to the user like it scan from left to right and top to bottom. We want the STEM images to match the simultaneously captured images from the microscope detectors and their layout.  I think that the layout in memory is also correct. x is row and y is column.

Would an example data set with nonsquare shape be the best way to make sure this is all correct?

**Comment by cjh1** [comment]
@ercius Thanks for the confirmation. @psavery has started to work on this using the tuple approach. Absolutely if you point us at a non-square scan that would be a good test case. We are also going to document the python functions and spell out our conventions, which will go along way to avoided confusion.
