### ISSUE TITLE
Add doc strings to all public python functions

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/stempy#107]
and setup readthedocs ...

**Comment by cjh1** [comment]
I think we should use sphinx here for its ability to generate documentation from doc strings. I would like to use mkdocs, but it doesn't have great support for API documentation. 

Here is the getting started guide for sphink: https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html

**Comment by cjh1** [comment]
I think we can still use MarkDown with sphinx.

**Comment by ercius** [comment]
I use sphinx on ncempy. The auto api documentation generation is very
useful. It can be difficult to get up and running though and I think I
still am not doing it right.

**Comment by psavery** [comment]
As a side note here, I used a [markdown to rst converter](https://pypi.org/project/m2r/) for one file we had already written in markdown, and it worked very well!
