### ISSUE TITLE
Strange STEM Images from PyReader

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/stempy#111]
The HDF5-reading PyReader seems to be producing strange STEM images for our test dataset, which are probably not correct. I am not sure whether the issue is in our saving of the raw data to the HDF5 file, or if it is in the PyReader itself.

STEM Images from PyReader
=======================

0 - 288 radii:
![image](https://user-images.githubusercontent.com/9558430/73386399-c70beb80-429c-11ea-9eaa-5a5fd85145b9.png)

40 - 288 radii:
![image](https://user-images.githubusercontent.com/9558430/73386405-cb380900-429c-11ea-8428-cbbf1f39eb11.png)

Correct STEM Images
=================

0 - 288 radii:
![image](https://user-images.githubusercontent.com/9558430/73386434-d68b3480-429c-11ea-89cc-7963ec1ec062.png)

40 - 288 radii:
![image](https://user-images.githubusercontent.com/9558430/73386447-db4fe880-429c-11ea-80e5-f86d2739f05d.png)

**Comment by ercius** [comment]
what code did you run to produce your images? Those look very strange

**Comment by psavery** [comment]
@ercius It is using [this file](https://github.com/OpenChemistry/stempy/blob/master/examples/hdf5Reader/reader_hdf5.py). The HDF5 file it is running on is about 16 GB in size (it contains the raw data).

**Comment by psavery** [comment]
Here's one thing that we might want to change at some point with the PyReader. It looks like [here](https://github.com/OpenChemistry/stempy/blob/7f4df7fe9abcf77142ca5942a22bf19e9121b8cb/python/stempy/io/__init__.py#L60-L61), it needs STEM images to already exist in the HDF5 file in order to get the scan dimensions. We might want to be open to the possibility of STEM images not being there, I'm not sure...

**Comment by psavery** [comment]
So I determined the cause of the error. The image numbers were not being saved to the HDF5 file, and that was causing the PyReader to use incorrect image numbers.

I think we can fix this in one of three ways:

1. Save the scan positions as an extra dataset at the root of the HDF5 file. We would do that [here](https://github.com/OpenChemistry/stempy/blob/11596e0edf582853e80370a6ac54d3e380ecafda/python/stempy/io/__init__.py#L98-L124), and that is what is currently expected [in the pyreader code](https://github.com/OpenChemistry/stempy/blob/11596e0edf582853e80370a6ac54d3e380ecafda/python/stempy/io/__init__.py#L65-L68). This was not being done previously, and thus the PyReader was just assuming the image numbers were sequential.
2. Save the scan positions as an attribute on the raw dataset, and set up the PyReader to read that attribute.
3. Sort the raw images sequentially [here](https://github.com/OpenChemistry/stempy/blob/11596e0edf582853e80370a6ac54d3e380ecafda/examples/create_hdf5.py#L76) before passing them to `io.save_raw_data()`. This would make the PyReader assumption that the image numbers are sequential correct.

**Comment by cjh1** [comment]
@psavery In general the plan was to store the frames in the hdf5 file in frame order or save the position in a separate dataset, to allow for storing out of order or partial scans. So in this case ( for this file ) the frames  should be store in order. This is the section of code this supposed to ensure this, 
 I can see for a start the index seems to be hard coded to zero ( not sure that is the problem in this case) https://github.com/OpenChemistry/stempy/blob/master/stempy/reader.cpp#L605

**Comment by psavery** [comment]
@cjh1 and I spoke, and just to record some of the discussion here, I was actually using [this script](https://github.com/OpenChemistry/stempy/blob/11596e0edf582853e80370a6ac54d3e380ecafda/examples/create_hdf5.py) rather than [SectorStreamReader::toHdf5FrameFormat()](https://github.com/OpenChemistry/stempy/blob/ce09a3d29faeb093ea7fd76fdd422459e09e3abd/stempy/reader.cpp#L571). I think I will need to update the script to sort the frames in order.

I'm going to take a look at the hard-coded index as well.
