### ISSUE TITLE
get scan information from reader

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#119]
When I do electron counting I need to input the scan dimensions manually. Can this be taken from the reader if the scan_dimensions are not given?

Or can we create a function that gets meta data information from a reader? stempy.io.get_metadata() which returns important information without reading the whole file? For example with 4D Camera data we only need to read the header of 1 file to get the relevant information for the entire scan.

**Comment by cjh1** [comment]
@ercius That is exactly what it should do with you don't provide `scan_dimensions`, is that not the case ( if so that is a bug )?

**Comment by psavery** [comment]
@ercius Yeah, try not providing `scan_dimensions` as an argument and let us know if it works.

**Comment by ercius** [comment]
I'll try this today. Thanks for the reminder!

**Comment by ercius** [comment]
It works as expected for electron counting. Sorry, I did not test that.

However, is there a way to get this information from the reader though? It would be nice to be able to look through the data and tell the user which dataset is which size without loading the entire data set?

**Comment by psavery** [comment]
@ercius Currently, you could extract the information from the header like this:

```python
block = reader.read()
scan_dimensions = block.header.scan_dimensions
```

Unfortunately, it does require reading a block of data (which may or may not be big, depending on the data set).

We could potentially add API to read only the header of a block. But it is not something that is there currently.

**Comment by ercius** [comment]
Reading a block of data is not a problem. That is relatively small and
quick. I don't think it's necessary to work a special API. Knowing where
the header data can be accessed is sufficient. Thanks!

**Comment by psavery** [comment]
Sounds great! I'll be closing this issue, then. Thank you!

**Comment by psavery** [comment]
@ercius One more thing. If you do read a block of data, the reader's internal state will change so that it will read the second block when `reader.read()` is called again. If you are going to pass the reader into a function for electron counting or stem image creation, make sure you first call `reader.reset()`, so that it will start from the first block.

**Comment by ercius** [comment]
@psavery Thanks for the info. I would not have thought of that.
