### ISSUE TITLE
PyReader requires "stem/images" for scan dimensions

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/stempy#126]
[Here](https://github.com/OpenChemistry/stempy/blob/7f4df7fe9abcf77142ca5942a22bf19e9121b8cb/python/stempy/io/__init__.py#L60-L61) in `get_hdf5_reader()`, the scan dimensions are determined by STEM images in the HDF5 file. However, it is not guaranteed that there will be STEM images in the HDF5 file (for instance, there may just be raw data).

We should come up with a way to either maybe save the scan dimensions into the HDF5 file, or have the user pass the scan dimensions in and use those for `get_hdf5_reader()`.

This issue comes from [this comment](https://github.com/OpenChemistry/stempy/issues/111#issuecomment-584650279) in #111.

**Comment by cjh1** [comment]
@psavery I though we where saving the scan dimensions are attributes in the HDF5 file?

**Comment by psavery** [comment]
@cjh1 I do see [from the documentation](https://stempy.readthedocs.io/en/latest/StempyH5Format.html) that it is being saved in `electron_events/scan_positions` as the `Nx` and `Ny` attributes. So we could potentially extract it from there as well, but it would only be there if the HDF5 file contained electron counted information.

It's also present if the raw data at `/frames` if it is in the square format (the 4-D format, where the scan dimensions will be the first and second dimensions).

I don't think it's saved anywhere else, though. It wouldn't be present if the HDF5 file only contains raw data, and it is it the 3D format.

**Comment by psavery** [comment]
From my discussion with @cjh1:

To do: create an attribute on `/frames` in the HDF5 file that indicates the scan dimensions.
To do: try to make dimension attributes into tuples if possible, but separate attributes if not.
