### ISSUE TITLE
Maybe add documentation for reader versions

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/stempy#132]
Currently, they are just `FileVersion.VERSION1`, `FileVersion.VERSION2`, etc. It might be good to add some documentation.

**Comment by ercius** [comment]
@psavery @cjh1  This is a good idea. Where would documentation like this live? I can add descriptions of the headers. I already have them written down.

**Comment by cjh1** [comment]
I think we could document it in a new rst file [here](https://github.com/OpenChemistry/stempy/tree/master/docs/source). If you have the description to had that would be great, we can also get it from the code. We can then add some description of the various versions, which might involve a little archaeology.
