### ISSUE TITLE
create_stem_images with multiple detectors not working

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#136]
I can get stempy.image.create_stem_images() to work if I only use 1 value for inner and outer radii. However, if inner and outer radii are a tuple then I get this error:

Im using electron counted sparse data loaded from a hdf5 file. So, `ee` is a ndarray of sparse data saved using `stempy.io.save_electron_counts()`

This works:
`ims = stim.create_stem_images_sparse(ee, 0, 100,scan_dimensions = scanSize,frame_dimensions=(576,576),center=(307,282))`

This does not work:

`>>> ims = stim.create_stem_images_sparse(ee,(0,100),(100,200),scan_dimensions = scanSize,frame_dimensions=(576,576),center=(307,282))`

Here is the error:
```
create_stem_images(): incompatible function arguments. The following argument types are supported:
    1. (arg0: stempy::BlockIterator<stempy::StreamReader>, arg1: stempy::BlockIterator<stempy::StreamReader>, arg2: List[int], arg3: List[int], arg4: Tuple[int, int], arg5: Tuple[int, int]) -> List[stempy._image._image_uint64]
    2. (arg0: stempy::BlockIterator<stempy::SectorStreamReader>, arg1: stempy::BlockIterator<stempy::SectorStreamReader>, arg2: List[int], arg3: List[int], arg4: Tuple[int, int], arg5: Tuple[int, int]) -> List[stempy._image._image_uint64]
    3. (arg0: List[List[int]], arg1: List[int], arg2: List[int], arg3: Tuple[int, int], arg4: Tuple[int, int], arg5: Tuple[int, int], arg6: int) -> List[stempy._image._image_uint64]
    4. (arg0: stempy._image._electron_counted_data, arg1: List[int], arg2: List[int], arg3: Tuple[int, int]) -> List[stempy._image._image_uint64]
    5. (arg0: stempy::PyReader::iterator, arg1: stempy::PyReader::iterator, arg2: List[int], arg3: List[int], arg4: Tuple[int, int], arg5: Tuple[int, int]) -> List[stempy._image._image_uint64]
```

I think there is just an error with argument checking for this function.

**Comment by cjh1** [comment]
@psavery Can you take a look at this?

**Comment by psavery** [comment]
@ercius Could you try making the inner and outer radii into lists instead of tuples, and see if that fixes it?

I got a similar error for using tuples instead of lists. Maybe pybind11 is being a bit picky. We could potentially convert those arguments to lists inside `create_stem_images` to make it more robust.

Also, do you get a deprecation warning for using `create_stem_images_sparse`? We combined all of the `create_stem_images` functions into one `stim.create_stem_images()`, and it automatically determines whether to use the dense or sparse algorithm based upon the type of the input.

**Comment by psavery** [comment]
In the case of a numpy array, if the user defines `frame_dimensions`, it assumes the data is sparse. Otherwise, the data is interpreted to be dense.

**Comment by psavery** [comment]
@ercius Nevermind. I found a bug in the code. This should be fixed by #137.

Until you get the new image, you can use a list instead of a tuple. But both will work when #137 gets merged.

**Comment by cjh1** [comment]
@ercius I have push a new image with this fix.

**Comment by ercius** [comment]
Thanks! I did not think to try using lists instead of tuples. I did get the
deprecation warning, so Ill keep using the overloaded function instead of
create_stem_images_sparse.

Glad it was pretty easy to fix. Ill pull the new image today. Thanks!
