### ISSUE TITLE
core dump for electron counting using latest version

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#138]
Im getting a core dump when doing electron counting using an HDF5 file for input. Im using the latest singularity image to run the counting.

Here is the code Im using:
``` python
from pathlib import Path
import sys
import time

import numpy as np
import h5py

import stempy.io as stio
import stempy.image as stim

scanNum = sys.argv[1]
scanName = 'data_scan{}_gain.h5'.format(scanNum)

threshold = int(sys.argv[2])

dPath = '/mnt/nvmedata1/temp'
fPath = Path(scanName)

iPath = dPath / fPath

dark0 = np.zeros((576,576))

print('Opening: {}'.format(iPath))
with h5py.File(iPath,'r') as f0:

    # Electron count the data
    sReader = stio.reader(f0)

    print('start counting')
    t0 = time.time()

    ee = stim.electron_count(sReader,dark0,number_of_samples=1200,
                                            verbose=True,threshold_num_blocks=20,
                                            xray_threshold_n_sigma=175,
                                            background_threshold_n_sigma=threshold)
```

The initial testing for the distribution mean and sigma finishes correctly and the verbose output looks correct. Then it goes directly to a core dump.

The electron counting works properly when using the sector reader. So, its probably something that has to do with the hdf5 reader specifically.

**Comment by ercius** [comment]
@cjh1 Im uploading to Cori now. The file is:
.../ncemhub/4Dcamera/2020.03.13/data_scan16.h5

Its about 10GB.

**Comment by cjh1** [comment]
Thanks @ercius copying now ...

**Comment by psavery** [comment]
I was able to reproduce this, and I think I figured out the problem.

On the C++ side, we need to acquire the python GIL before we delete python objects. We weren't doing that in a couple of cases. I have a fix coming soon, and it fixes the crashing for me.

**Comment by cjh1** [comment]
@ercius The image is update with the fix.

**Comment by ercius** [comment]
awesome. Thanks so much!
