### ISSUE TITLE
feature request: read electron counts from h5 file

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#140]
Can we make the [ElectronCountedData](https://github.com/OpenChemistry/stempy/blob/1b3360fc114ddbc3a1ac9d70b5b461782bb523e9/python/stempy/image/__init__.py#L345) numedtuple available for use later? It would be great to provide the ability to be create a namedtuple which the user populates and stempy recognizes. Also, we can have a stempy.io function to load the electron counted data back into this same namedtuple form. Then the frame dimensions and scan dimensions will be placed correctly on import.

**Comment by cjh1** [comment]
@ercius We can take a look at this. Providing a function to load it into the namedtuple should be pretty straight forward, we would need to think about how to allow a user to create and populate their own, but we will come up with something.

**Comment by ercius** [comment]
@cjh1  thanks. I think that just loading the data back into the namedtuple would be sufficient. It should have the same signature as the originally created one so that it can be used in the stempy.image functions as well.

**Comment by cjh1** [comment]
@ercius This is now merged into master and I have updated the container. Note that we changed `save_electron_counts` to take the `ElectronCountedData` rather than just the raw data, so you don't has to pass the parameter separately.

**Comment by ercius** [comment]
That's exactly what I needed. Thanks! This makes analysis easier.
