### ISSUE TITLE
Validate numpy types, passing the wrong type currently causes a crash

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/stempy#157]

**Comment by cjh1** [comment]
@psavery I think this can be closed off, given the work you did in #178

**Comment by psavery** [comment]
@cjh1 Sounds good. Yeah, it is ensuring the `gain` and `darkreference` variables are cast to the right type. We can use that utility function more in the future if more things need to be cast.

**Comment by cjh1** [comment]
Fixed in #178
