### ISSUE TITLE
Deprecation warning from electron_count

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#161]
I get this warning when electron counting data:

/usr/local/lib/python3.7/site-packages/stempy/image/__init__.py:391: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  electron_counted_data.data = np.array([np.array(x, copy=False) for x in data.data])

**Comment by cjh1** [comment]
We should be able to clean this up.
