### ISSUE TITLE
stempy-jupyterlab plots not working

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#162]
Error when trying to show interactive plots in stempy-jupyterlab kernel

```python
%matplotlib widget

import matplotlib.pyplot as plt
plt.figure()
Error displaying widget: model not found
```

**Comment by cjh1** [comment]
I will take a look, this is on cori?

**Comment by cjh1** [comment]
I think its because we need to merge #155, I will do that and try.

**Comment by cjh1** [comment]
Yep, that fixed it. Should be good now.
