### ISSUE TITLE
squashfs problem

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#165]
I get this error when trying to run the singularity images on mothership6. Could be an update to the local singularity version (2.4.2-dist) but Im not sure.

```
>> sudo singularity exec stempy-latest.simg ls 
ERROR  : Unable to open squashfs image in read-write mode: Read-only file system
ABORT  : Retval = 255
```

Adding the -w option does not help. 

Google-fo did not bring up an answer.

**Comment by cjh1** [comment]
@ercius I will take a look at this today.

**Comment by cjh1** [comment]
@ercius I think this is a bug in that singularity version. I installed the latest (3.6.1) locally and issue goes away. These are the [instructions](https://github.com/hpcng/singularity/blob/master/INSTALL.md) I followed.

**Comment by ercius** [comment]
@cjh1 Thanks. Ill upgrade soon.

**Comment by cjh1** [comment]
Let me know if you run into any problems.

**Comment by ercius** [comment]
@cjh1 I got it working. I hope the distribution version will update to avoid manual building of singularity. Ill add this to the singularity instructions on the repo.

**Comment by cjh1** [comment]
It actually looks like singularity isn't packaged for the latest Ubuntu, so updated the instructions would be great.

**Comment by ercius** [comment]
See #167 

That's weird. Are they removing support for it? Maybe docker is a better option?

**Comment by cjh1** [comment]
I don't think they are removing support for it. Not sure why it not being package, 20.04 is relatively new, so may be the maintainer hasn't got things working with it yet. Either way we should stick with it, singularity is a better choice for what we are doing.

**Comment by ercius** [comment]
Great. Building it is not too hard. Thanks!
