### ISSUE TITLE
Build image with specific compile options for KNL nodes

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/stempy#171]

**Comment by cjh1** [comment]
@ercius I have built an image that sets the architecture to "KNL" when we build stempy in our container. The general consensus seems to be that this will not make much difference as gcc is bad a vectorising from knl. However, it is probably worth giving it a go, so if do any runs cori soon you could give it a go and compare. The other option would be to build everything natively on cori and see what that gives us. This would be a little more work given that there a compile errors with the cray compiler, so I say wait until we see how the container performs.

**Comment by cjh1** [comment]
Sorry this is the image name:

```
openchemistry/stempy:knl
```

**Comment by ercius** [comment]
@cjh1 I ran into a couple of problems with this for a 512x51 scan.

I ran into an error using the KNL debug nodes:
`OpenBLAS Warning : The number of CPU/Cores(272) is beyond the limit(256). Terminated.`
This only happened when I submitted a script to the KNL-debug nodes.

I still got the out of memory error in interactive mode on a KNL. I just set threaded = 1 and let the machine choose the number of threads. The script I use is in `ncemhub/4Dcamera/4dc_processing/cori` as electron_count_cori.sh and electron_count_cori.py

How are you testing this? What parameters do you use?

**Comment by ercius** [comment]
In interactive more I ran:
` shifter --image openchemistry/stempy:knl python3 /global/project/projectdirs/ncemhub/4Dcamera/4dc_processing/cori/electron_count_cori.py -l /global/cscratch1/sd/percius/2020.06.03/ -t 4 -s 15`

This ran out of memory in a few minutes)

I also changed the number of threads:
 - 5 threads barely hit memory because it was probably reading in pretty slow. I have not idea how long it would take to count.
 - 144 threads (2 per file) was filling up memory very fast (few minutes).
 - 72 threads (1 per file) also filled up memory equally as fast (few minutes).

Any suggestions as to the number of threads to use?

**Comment by cjh1** [comment]
@ercius I have been looking at #172, I have a few things I would like to try out to avoid these out of memory issues. In #172 it seemed that 15 was the sweet spot.

**Comment by ercius** [comment]
@cjh1 15 threads still gave me issues. I got up to 90% memory usage for the 512x512 for the data set Im testing. I killed it before it ran out of memory.

**Comment by cjh1** [comment]
Strange, this what I have been using for `ncemhub/4Dcamera/2020.10.05/data_scan0000000231`:

```
#!/bin/bash
#SBATCH --qos=debug
#SBATCH --time=00:30:00
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1
#SBATCH --constraint=knl
```
With the number of threads set to 15. 

Hopefully I can come up with something in #172, that will make this more robust.

**Comment by ercius** [comment]
Ok. I'll try that too see if I can replicate what you have done. Maybe I'm
doing something wrong or my data set is different in some way.

I'll try it tomorrow.

**Comment by cjh1** [comment]
@ercius I would wait, I am close to having something for #172, which should resolve the out of memory issues with larger numbers of thread, fingers crossed.

**Comment by ercius** [comment]
@cjh1 fingers crossed. I hope this works!

**Comment by cjh1** [comment]
Closing as this is no longer relevant
