### ISSUE TITLE
Out of memory on Cori nodes

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#172]
Getting out of memory issue on Cori when counting 163 GB (512x512) sized scan.  Using 20 threads the nnode runs out of memory. Using 15 threads is successful.

Same problem with 20 threads when using `gain=None` and `gain=np.ones((576,576),dtype=np.float32)`

Would be good to check the dtype used in memory for different options:
- [ ] No gain and no dark
- [ ] Dark, no gain
- [ ] Gain and dark

**Comment by cjh1** [comment]
You mentioned that this is with `VERSION4`, is this correct?  

So in the case of the first two that data will be treated as `uint16`, only the introduction of the gain will push the size to `float32`. In the case of subtracting the dark reference, we statically cast back to `unit16` ( truncate ) which may or may not be the right think to do? However, this is what we have been doing from the start. We have an issue that we will work on next to accept `float32` for the dark reference as well.

So in terms of the out of memory issue. If this is running on a knl node we have 96gb to play with. The main memory usage for the threaded reader is to cache the partial frames as they reconstructed ( they are removed from the cache and counted once they are complete ). So there are a couple of things that could cause problems in terms of the dataset. If there is large loss ( lots of partial frames ) or if the frame quadrants are for some reason jumbled across the multiple files ( as in we have to maintain a lot of partial frames for the entire read ). How many files is this data set spread across? In general more threads is also going to increase the memory usage as you are seeing.

**Comment by ercius** [comment]
> You mentioned that this is with VERSION4, is this correct?

Yes. And if that makes a difference then we should not bother fixing this. I'm only interested in VERSION5 going forward. I was using an older experiment as an example of a folder full of data that was not fully analyzed and Im testing submitting many counting jobs at once.

>So in the case of the first two that data will be treated as uint16, only the introduction of the gain will push the size to float32. In the case of subtracting the dark reference, we statically cast back to unit16 ( truncate ) which may or may not be the right think to do? However, this is what we have been doing from the start. 

Everything you describe here is what I would expect the code to do. I was getting the problem on Cori KNL nodes and not on mothership6. Probably one has more memory than the other.

> We have an issue that we will work on next to accept float32 for the dark reference as well.

I dont think there is any need for this. Dark can be uint16 and gain should be float32.

I think that the only thing I wanted to do with the dark was to have the input allow uint16. Right now I think it requires it to be float64 (default of np.zeros()). Sorry if I was not clear on that particular point.

**Comment by ercius** [comment]
Is the counting code doing a "round robin" through the file list or is it reading each file completely into memory? If the latter then we will run out of memory unless the files are read in a random order. For the 512x512 the sectors are spread throughout each file from the start to the end of the scan. 

It likely depends on how the threads go through the files. This probably needs to be optimized (as you said earlier) for the KNL nodes to avoid running out of memory.

**Comment by ercius** [comment]
I just confirmed that the files I was testing originally have 99.9881...% completion. So, that not the problem.

If I read entire files into memory and plot the completeness of the full scan read you can see it approaches 1 with an exponential-like curve. See below a plot of the number of full images on the y-axis and the x axis is the number of files read where the file list is randomized using `random.shuffle()`

![Figure 6 (5)](https://user-images.githubusercontent.com/15657108/91111470-717e9e00-e635-11ea-91f4-20adfeb6d3ca.png)

Ill have to try with a sorted list, but I bet its not nearly as good. It will be flat for a long time until 3/4 of the data is read in. It tends to sort on the part of the filename with the module (i.e. module0to1). So, you will only get full images until you get to the first module3to4 file. Then they will all complete.

Not sure what the best way to do this is if we have 96 GB. Im not sure how the threads interact with the files.

**Comment by cjh1** [comment]
Thanks this is a useful plot. So the way the reader works is to open all the files and reads a block at a time from each file in a round robin fashion, this is done in parallel across the threads. So I guess as you increase the number of threads you increase the number of partial frames that may have to held in the cache at a time.

**Comment by ercius** [comment]
Seems to me like the cache should be getting cleared pretty quickly then. Checking that the cache is getting properly cleared is something to keep in mind when optimizing for the KNL nodes.

**Comment by cjh1** [comment]
@ercius I can add some instrumentation and dig into this further, can you point me at the dataset?

**Comment by ercius** [comment]
@cjh1 

I have tested with both VERSION4 and 5. The problem is the same. I think concentrating on 5 is better. However:

For VERSION4:
ncemhub/4Dcamera/2020.02.05/data_scan301_*.data

For VERSION5:
ncemhub/4Dcamera/2020.06.04/data_scan0000000050_*.data

They are both 513x512 scans.

**Comment by cjh1** [comment]
@ercius I would like to take a look at this, it seem that the 2020.06.04 scan is no longer there. Is there another similar size scan I could use. Were you just electron counting and writing to HDF5?

**Comment by ercius** [comment]
@cjh1 I think I deleted that because I thought we were done with it. Sorry about that.

I have lots of other 513x512 scans. Try:
ncemhub/4Dcamera/2020.10.05/data_scan0000000231*

If you want a 1kx1k:
ncemhub/4Dcamera/2020.10.05/data_scan0000000229*

**Comment by cjh1** [comment]
@ercius  Thanks I will see if I can recreate using that dataset.

**Comment by ercius** [comment]
counted H5 files are in the same directory to compare to.

**Comment by cjh1** [comment]
@ercius I have started to look at this, I can recreate the out of memory situation. Quick question, for scan231, is it a single frame per scan position?

**Comment by ercius** [comment]
@cjh1 Yes. 231 and 229 are both 1 frame per scan position.

**Comment by ercius** [comment]
This is fixed via #183
