### ISSUE TITLE
Threaded counting produces incorrect result

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#173]
We were counting some data and noticed weird behavior which we thought was a problem with the detector or a dark reference or something else. However, we can remove the artifacts when we use the non-threaded counting code.

We have other examples with the pattern centered, so that is not an issue.

Here is a sum of about 1000 patterns from a recent scan using the threaded code:
![Figure 4 (3)](https://user-images.githubusercontent.com/15657108/92950619-d5fd7380-f411-11ea-9289-2e9b83ec4f95.png)

Here is a sum of about 1000 patterns from the same data set counted using the non-threaded code:
![Figure 3 (2)](https://user-images.githubusercontent.com/15657108/92950692-f0cfe800-f411-11ea-83ba-ebd162332177.png)

These were counted using the the latest image on mothership6. The date of the image file from `ls-lf` is August 21st.

Looks like there is some issue with the memory not being cleared properly for each counted frame.

**Comment by cjh1** [comment]
@ercius Do you have the notebook/script you are using for this? I am guess the problem was introduced with the recent dark reference  changes. I would like to retry with an image before those changes so we can try and track it down.

**Comment by ercius** [comment]
@cjh1 Where do you want to do the testing? On mothership6? We are using it today, but I can point you to where the data for the scan Im showing is. Or we can provide a smaller scan since that one is 512x512 and takes 5 minutes to count.

**Comment by cjh1** [comment]
@ercius Smaller scan would be great, if you can point us at the data.

**Comment by ercius** [comment]
Ok. Ill take a smaller scan when I get a chance soon. Then Ill point you to the data. Are you going to download the data locally and run things there? Or do you need access to mothership6?

**Comment by cjh1** [comment]
@ercius We would like to download the data  if possible.

**Comment by ercius** [comment]
@cjh1 No problem at all. Please download away!

The files are on mothership6 at:
/mnt/hdd1/2020.09.10-Kitware-test/

scan126. Its 128x128 and only about 11GB.

I also have the counted data in there from the threaded and non-threaded stempy function.

I also copied the python scripts I use to do the counting in that directory in case there is some issue with my script for the threaded function run.

Let me know if you need anything.

Here are the screen shots of the sum of all counted data for threaded and non-threaded:
Threaded
![image](https://user-images.githubusercontent.com/15657108/92969468-e58cb480-f431-11ea-8c6d-9e56cb014c74.png)

non-threaded:
![image](https://user-images.githubusercontent.com/15657108/92969546-048b4680-f432-11ea-84db-66092c592fa2.png)

**Comment by cjh1** [comment]
@ercius Thanks, download now.

**Comment by cjh1** [comment]
Do you have the code you are using to create the plots?

**Comment by ercius** [comment]
Ill copy and paste the relevant pieces here. Hopefully no major typos are added:

```python
import stempy.io as stio
import stempy.image as stim

electron_events = stio.load_electron_counts(str(dPath / fPath))

# Calculate a summed diffraction pattern
start = 0
end = -1
dp = stim.calculate_sum_sparse(electron_events.data[start:end], electron_events.frame_dimensions)

fg, ax = plt.subplots(1,1)
ax.imshow(dp)
```

**Comment by cjh1** [comment]
Thanks!

**Comment by cjh1** [comment]
@ercius So I have started to take a look at this and unable to recreate your images above. It seems like the electron counts are very different. I even tried using image on your server. I am running the following to do the electron count

```
singularity exec -B /mnt /home/daquser/stempy_latest.sif python3 ~/electron_count_nothread.py 126 4
```

Is this the same image you were using? And are you using a threshold of 4?

**Comment by ercius** [comment]
@cjh1 This command will *not* show the problem:
`singularity exec -B /mnt /home/daquser/stempy_latest.sif python3 ~/electron_count_nothread.py 126 4`
It uses the non-threaded counting code.

This is the command I use which does show the problem:
`singularity exec -B /mnt /home/daquser/stempy_latest.sif python3 ~/electron_count.py 126 4`
Make sure that the backend keyword is set to 'thread' in that script.

**Comment by ercius** [comment]
@cjh1 I was just able to recreate this on mothership6. I moved my processing scripts to a different directory called 4dc_processing.

I ran this code from the daquser account (with threading enabled):

`/usr/local/bin/singularity exec -B /mnt ~/stempy_latest.sif python3 ~/4dc_processing/electron_count.py 126 4`

The data was written to /mnt/hdd1/data_scan126_th4.0_electrons_001.h5. I will leave the script as-is so you can hopefully just copy and paste the above command.

See if you can get the output below from the h5 file above. Then see if you can recreate the h5 file with and without threads.

This is the output:
![image](https://user-images.githubusercontent.com/15657108/93275119-e34b9280-f770-11ea-8056-2b9b7fe706a0.png)

**Comment by cjh1** [comment]
Thanks @ercius, I will try it out tomorrow.

**Comment by ercius** [comment]
@cjh1 Looks like this is fixed due to a couple of recent commits and pulls. I tried it on the test data on ms6. Im going to run a larger set of data which I know did not work previously. I think its fixed though.
