### ISSUE TITLE
Update images in readme

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/stempy#180]
@ercius It looks like the URLs for the images you added to the readme are no longer working. Do you have the original images, we can add them to the repo or somewhere more permanent.

**Comment by ercius** [comment]
I dont have those images anymore. I will recreate them and update the readme to include the newest functions to replace some of this code. Then Ill add them to the repo. Where would you prefer data like that be located?

**Comment by cjh1** [comment]
@ercius Sounds good, we have `docs` directory so lets do, `docs/images`?

**Comment by ercius** [comment]
sounds good to me. Ill make a pull request soon.

**Comment by ercius** [comment]
@cjh1 see #182.

**Comment by ercius** [comment]
@cjh1 This can be closed #182
