### ISSUE TITLE
write_hdf5 error

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#188]
Im getting this error on KNL nodes when trying to convert a raw file into a HDF5 file
> OpenBLAS Warning : The number of CPU/Cores(272) is beyond the limit(256). Terminated.

We saw this before when counting and it happens when I use the latest image, the debug image and when I try to set the threads to a low number like 15. 

Is there a way around this? Its not a common operation but we need to do it sometimes. Thus, it does not have to run super fast, but it would be nice to have working.

**Comment by ercius** [comment]
We saw this in #171 and it probably has to do with the optimizations we are doing for electron_count.

**Comment by ercius** [comment]
I forgot to mention that this does not happen in an interactive session. Only for batch nodes. Im not sure why.

**Comment by cjh1** [comment]
@ercius Can you try added the following to your submission script:

`export OPENBLAS_NUM_THREADS=256`

**Comment by ercius** [comment]
That did not work. I still get the error with the same number (272).

```bash
#!/bin/bash
#SBATCH -q debug
#SBATCH -C knl
#SBATCH -t 00:10:00
#SBATCH --image=openchemistry/stempy:debug
#SBATCH --account=ncemhub
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1

export OPENBLAS_NUM_THREADS=256

python3 /global/project/projectdirs/ncemhub/4Dcamera/4dc_processing/cori/tohdf5.py 53
```

I thought that is was odd that it works in interactive mode. So, I removed the `#SBATCH --image=` and changed the command to `shifter --image=openchemistry/stempy:debug python3 global/project/projectdirs/ncemhub/4Dcamera/4dc_processing/cori/tohdf5.py 53`

That worked. I also removed the `export` line and it still worked. 

Maybe the export needs to be included in the shifter image somehow?

This is what worked:
```bash
#!/bin/bash
#SBATCH -q debug
#SBATCH -C knl
#SBATCH -t 00:10:00
#SBATCH --account=ncemhub
#SBATCH --nodes=1
#SBATCH --tasks-per-node=1


shifter --image=openchemistry/stempy:debug python3 /global/project/projectdirs/ncemhub/4Dcamera/4dc_processing/cori/tohdf5_temp.py 53
```

**Comment by cjh1** [comment]
@ercius I think your first batch script is not running in shifter at all, its trying to run in the python installed on cori so will not get very far. I all using the `shifter --image=` form.

**Comment by cjh1** [comment]
@ercius I just want confirm that with `shifter --image` version we are not seeing the error? If so I think we can close this off?

**Comment by ercius** [comment]
@cjh1 Hmmm. I was misreading the examples of how to use shifter in batch scripts. I thought that the `#SBATCH --image` line in the first submission script would load the shifter image and then I would already be "inside" the image. Thus, I just needed to run `python` in the image.

The second script with `shifter --image` worked properly. So, we can close this up.  Thanks!
