### ISSUE TITLE
Multi-pass

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#190]
Tracking development of multi-pass backend for improved counting of 4D Camera data

The code looks through all the data to find where each sector is so it can be read in order. This takes some time but for SSDs (minimal seek time) it will improve the ability to read and count the data in order. This reduces the memory use and seems to speed the process up.

Using a recent 512x512 scan on mothership6:
- no multi-pass: 190 seconds
- with multi-pass: 120 seconds

**Comment by ercius** [comment]
@cjh1 Not sure where we are at with this. Is there an image on Cori that I can use to test the burst buffer and/or using multiple nodes? We are trying to test a workflow to get data to NERSC burst buffer rapidly. It would be interesting to try counting from teh BB then too.

**Comment by cjh1** [comment]
@ercius Sorry this is still a development branch. I need to clean it up and add support for multiple scans at a give position, then I was going to look at the parallel version. I will try to clean it up this week. In meantime I have pulled the current development image that you tried out on mothership onto cori so you can try it with BB. The image is `openchemistry/stempy:multi-pass`, don't be surprised if the performance isn't great ( it wasn't with scratch ). The win will hopefully be when we have a parallel version.

**Comment by ercius** [comment]
I got this working on Cori. A 512x512 was counted in about 5 minutes using the multi-pass algorithm using the burst buffer to read the files.  That is not too bad! It would be great to see what the parallel version can do.

**Comment by cjh1** [comment]
@ercius Thanks for running that test, that is a great result. I am working on the parallel version as we speak, I will keep you posted. What scan did you use for that test?

**Comment by ercius** [comment]
I used scan 126 in ncemhub/4Dcamera/2020.12.07/

**Comment by ercius** [comment]
I think this can be closed. Its merged and being used in production now.
