### ISSUE TITLE
Jupyter docker image issue

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#201]
I updated the stempy jupyter image just now. It looks like stemy.io and stempy.image can't be imported. I can import stempy.  I am able to load stempy.io and stempy.image in the non-jupyter version.

I will revert to the older version so this is not critical. But it would be good to look at soon.

**Comment by cjh1** [comment]
I think this is related to the new wheels, sorry about that. @psavery is going to take a look.

**Comment by psavery** [comment]
Hi @ercius. Do you mean the [stempy-scipy-notebook image](https://hub.docker.com/r/openchemistry/stempy-scipy-notebook)? I was able to start up a jupyter notebook with it and load the modules.

![Screenshot from 2021-03-08 15-38-32](https://user-images.githubusercontent.com/9558430/110385936-366a1800-8025-11eb-90b5-c42ab9bef59f.png)

Let me know if you are doing something different.

**Comment by cjh1** [comment]
@ercius that would correspond to the following image `openchemistry/stempy-scipy-notebook` you would have pulled.

**Comment by ercius** [comment]
@cjh1 I pulled that image. On mothership6 Im running:
`singularity exec -B /mnt:/mnt,/tmp:/home/jovyan ~/stempy-scipy-notebook_latest.sif jupyter lab`
Then I connect to the Jupyter Lab server. 

Then `import stempy` works but `import stempy.io as stio` and `from stempy import io` do not work.

I just re-pulled the image and got a lot of changes. However, I still can not import `stempy.io`.

Here is some information about the image:
```bash
>> singularity inspect stempy-scipy-notebook_latest.sif
org.label-schema.build-date: Wednesday_10_March_2021_9:20:27_PST
org.label-schema.schema-version: 1.0
org.label-schema.usage.singularity.deffile.bootstrap: docker
org.label-schema.usage.singularity.deffile.from: openchemistry/stempy-scipy-notebook:latest
org.label-schema.usage.singularity.version: 3.6.1+11-g7c3204ca4
```

**Comment by psavery** [comment]
@ercius I see, I was able to reproduce this in singularity. I guess this might be a specific problem to singularity. I'll look into it.

**Comment by cjh1** [comment]
@ercius This should now be resolved, please try pulling the latest `openchemistry/stempy-scipy-notebook` image.

**Comment by ercius** [comment]
Fixed! Thanks!
