### ISSUE TITLE
NERSC jupyter interactive plotting not working

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#207]
The interactive plotting on Jupyter@NERSC is not working anymore. I used to use `%matplotlib widget` at the start of a notebook to get it to work. This might have to do with the upgrade to JupyterLab 3.0. 

We might need to update ipywidgets or something else in the Jupyter-notebook kernel and pull it to NERSC to be compatible with JupyterLab 3

**Comment by ercius** [comment]
The error is:
`Error displaying widget: model not found`

**Comment by cjh1** [comment]
@ercius I bumped the one package that seems to be effected by the jupyterlab 3 upgrade. Let me know if that works for you.

**Comment by ercius** [comment]
perfect. thanks!
