### ISSUE TITLE
Modify sparse data result for scans with multiple positions

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#208]
we have the ability to acquire multiple frames per scan position and stempy will count that data. It currently combines all events from the same scan position into one event list in the final sparse data set. See #176. 

I would like to change this behavior so that each frame is a separate list and is associated with a scan position. This capability is builtin to the sparse data format but not user. See description [here](https://stempy.readthedocs.io/en/latest/StempyH5Format.html).

If we take 1 frame per scan position then `len(frames) == n*m` where the scan is nxm number of scan positions. `scan_positions` is then a list of `[0,1,2,3,...,n*m]`

If we take 2 then `len(frames) == 2*n*m` and `scan_positions` should be a list like `[0,0,1,1,2,2,3,...,n*m,n*m]`

To avoid breaking older analysis code I think we might want to indicate the new sparse data is different somehow. Or maybe provide the option to save the sparse data set in the old way (combining all frames into one event list) and the new way described above.

**Comment by psavery** [comment]
@ercius, could you provide me with a test dataset?

**Comment by ercius** [comment]
Yes. Try this one:
distiller scan id 505
https://distiller.lbl.gov/scans/505

the counted data is on NERSC in the ncemhub/distiller/distiller/counted/2022.01.04/data_scan5_...

There are 2 frames per position for that scan.

**Comment by psavery** [comment]
@ercius Is the raw data available for this? I'll need that to test changes to the electron counting methods in stempy.

**Comment by ercius** [comment]
no...that is deleted. Ill have to take a new data set to be sure we have exactly what you need. Ill take a small data set soon, store the raw data on NERSC, and send you the location.

**Comment by psavery** [comment]
Sounds great, thank you Peter!

**Comment by psavery** [comment]
@ercius I'd also like to confirm that I'm giving the `SparseArray` operations the correct behavior for scans with multiple frames per scan position.

I'm going to make up an example. Let's say we have two scan positions and each position has two 2x2 frames. At scan position 0, the sparse arrays are `[0]` and `[0, 2]`, and at scan position 1, the sparse arrays are `[0]` and `[0, 1]`. Can you confirm if all of these are correct?

1. The expanded dense arrays for the two scan positions would be:
```python
# position 0
[[2, 0],
 [1, 0]]

# position 1
[[2, 1],
 [0, 0]]
```

2. The sum would be:
```python
[[4, 1],
 [1, 0]]
```

3. The max would be:
```python
[[2, 1],
 [1, 0]]
```

4. The min would be:
```python
[[2, 0],
 [0, 0]]
```

5. The mean would be:
```python
[[2, 0.5],
 [0.5, 0]]
```

**Comment by ercius** [comment]
@psavery This all looks correct to me.

**Comment by psavery** [comment]
@ercius I've added those examples to the tests that are performed, along with a few others, in #228.
