### ISSUE TITLE
Jupyter kernel missing widgets for interactive plotting

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#213]
The jupyter kernel on NERSC needs to be updated for interactive plotting. It is a similar issue to #207 and #134.

**Comment by ercius** [comment]
This is still not working.

The default kernel on Jupyter@NERSC has these versions:
```python
import ipywidgets
print(ipywidgets.__version__)
import ipykernel
print(ipykernel.__version__)
import ipympl
print(ipympl.__version__)
import matplotlib
print(matplotlib.__version__)
```
7.6.3
5.3.4
0.8.1
3.3.4

stempy-jupyter has these versions:
7.6.3
5.1.2
0.7.0
3.1.1

I see that the versions were bumped in #215, but my kernel does not reflect that.
`ipykernel==6.4.2 ipympl==0.8.1 matplotlib==3.4.3`

**Comment by cjh1** [comment]
The kernel should be called `stempy-jupyterlab`, can you past the contents of: `~/.local/share/jupyter/kernels/stempy-jupyterlab/kernel.json` and/or `~/.local/share/jupyter/kernels/stempy-jupyter/kernel.json`. Looks like you aren't picking up the right shifterimage ...

**Comment by ercius** [comment]
```
percius@cori01:~> cat ~/.local/share/jupyter/kernels/stempy-jupyterlab/kernel.json
{
    "argv": [
        "shifter",
        "--image=openchemistry/stempy-ipykernel:latest",
        "/usr/local/bin/python3",
        "-m",
        "ipykernel_launcher",
        "-f",
        "{connection_file}"
    ],
    "display_name": "stempy-jupyterlab",
    "language": "python"
}
```

Looks like Im getting `stempy-ipykernel` instead. Can I just change the line to:
`"--image=openchemistry/stempy-jupyterlab:latest"`

**Comment by cjh1** [comment]
@ercius Don't worry, I can just push to that tag as well, give me a few minutes.

**Comment by cjh1** [comment]
@ercius I updated that tag as well ... let me know if it now works for you.

**Comment by ercius** [comment]
Works for me now. Thanks!
