### ISSUE TITLE
com_sparse does not work with bin_scans

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#239]
`SparseArray.bin_scans()` does not change the `SparseArray.data` element. This means that `com_sparse` is unable to work with data that is binned in this way. The algorithm needs to be changed to since center of mass of each pattern is not separable.

**Comment by ercius** [comment]
- [ ] Change algorithm to work with bin_scans()
- [ ] Test it works with multiple scans per position
- [ ] update input to allow SparseArray() without needing extra keywords

**Comment by psavery** [comment]
@ercius Can I update it to take just a sparse array and the `crop_to` argument, or do you want to preserve the other arguments as options?

**Comment by psavery** [comment]
(Note, if we preserve the other arguments, we will most likely need to add a `scan_positions` argument as well to take into account the scan positions now).

**Comment by ercius** [comment]
I think that we can just use the SparseArray on second thought. So, you can remove the other arguments.

What will happen to older data in the old format? Will that still work or do we need to use 1.1.0?

**Comment by psavery** [comment]
So, I think data in the older format will still work as long as there are not multiple frames per scan position.

However, if we do have a bunch of data in the older format with multiple frames per scan position, I'm happy to also write some code to convert it to the new format. It could also be relatively easy to detect as well - we can check to see if there are any duplicate values in any of the sparse frames (which would imply it's using the older format), and then convert it to the new format.

If there's only one frame per scan position, then the new format and the old format are identical.

**Comment by psavery** [comment]
Hi @ercius. I think I have this working, along with a test. But just to confirm, I wanted to provide you my example and the results. It should match the results of using the old format with the previous version of the function.

For a SparseArray of `scan_shape == (2, 1)` and `frame_shape == (2, 2)`, and `scan_positions == (0, 0, 1, 1)`, where the two sparse frames at scan position 0 are `[0]` and `[3]`, and the two sparse frames at scan position 1 are `[0]` and `[0, 1, 2]`, the expanded frames would look like these (in order):
```python
# scan position 0
[[1, 0],
 [0, 0]]

[[0, 0],
 [0, 1]]

# scan position 1
[[1, 0],
 [0, 0]]

[[1, 1],
 [1, 0]]
```

And the COM for each scan position would be this:
```python
[[ 0.5], [ 0.5]] # scan position 0
[[0.25], [0.25]] # scan position 1
```

**Comment by ercius** [comment]
@psavery Yes. That all looks correct to me. A good test of the sparse algorithm is to do the COM in the sparse domain and compare that to the COM calculated from the dense pattern (with many zeros) of those same frames added together. Your example works perfectly!

**Comment by psavery** [comment]
@ercius I added a test example in that PR as well now that also compares the `com_sparse()` results for real data to `scipy.ndimage.center_of_mass()` results for the fully expanded array.

**Comment by ercius** [comment]
Nice. Maybe use `stempy.image.com_dense()`?

**Comment by ercius** [comment]
> However, if we do have a bunch of data in the older format with multiple frames per scan position, I'm happy to also write some code to convert it to the new format. It could also be relatively easy to detect as well - we can check to see if there are any duplicate values in any of the sparse frames (which would imply it's using the older format), and then convert it to the new format.

We do have a lot of that data which might still need to be processed or being processed. If you can test for that then it would be worth converting to the 2.0 type upon reading with SparseArray.from_hdf5(). Or maybe add an option to load as v2.0 or v 1.0? What do you think is best?

Along these lines, we should probably add a version number to the stempy HDF5 hierarchy.

**Comment by psavery** [comment]
@ercius That all sounds good. I've written up a function that can check if the data is in the v1 format, and another function that can convert the data to the v2 format. I'll add these to the PR soon.

We can start adding a version number to the HDF5 files. If the version number is missing from the HDF5 file, it can run the function to check if the data is in the v1 format. But if the file does contain a version number, we won't need to check. So the newer versions of the HDF5 files won't need to be checked.

**Comment by ercius** [comment]
I think that is a great idea!

**Comment by psavery** [comment]
> I think that is a great idea!

Okay! I have updated #241 to do just that. And it includes a test too, that converts some real data of the old format to the new format.
