### ISSUE TITLE
SparseArray v3 looping over each frame

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#251]
Im also not that clear on the best way to loop over the sparse data. Maybe you can help me out.

I often want to do something to each frame in the sparse domain and I want to make a new SparseArray out of the result. Here is an example:

```python
centered = []
for eev, x, y in zip(experiment.data, z0_round.ravel(), z1_round.ravel()):
    centered2 = []
    for ev in eev:
        evx, evy = np.unravel_index(ev, experiment.frame_shape)
        evx_centered = evx - y # need to flip x and y
        evy_centered = evy - x

        # Some events will get pushed off the detector by the shift. Remove them
        keep = (evx_centered < experiment.frame_shape[0]) & (evx_centered >= 0) & (evy_centered < experiment.frame_shape[1]) & (evy_centered >= 0)
        evx_centered = evx_centered[keep]
        evy_centered = evy_centered[keep]

        centered2.append(np.ravel_multi_index((evx_centered,evy_centered), experiment.frame_shape))
    centered.append(centered2)
centered = np.array(centered, dtype=object)
```

Im trying to shift each electron strike index by a few pixels in each dimension, but I want to do this without making the dense array (i.e. using np.roll). I make two lists and append to those then create a numpy object which seems inefficient. It works, but is there a better method?

**Comment by cjh1** [comment]
We could probably add some syntax sugar to take care some of the looping over frame, I was thinking about something `iterframes` in a similar vein to `iteritems`.

**Comment by ercius** [comment]
I think something like that would be useful.

**Comment by ercius** [comment]
@psavery These examples are exactly what I was looking for. I tried `zeros_like` but that did not work. `empty_like` is the right way to do it. Thanks!
