### ISSUE TITLE
Add row-dark operation to counting

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#258]
Each frame has a global dark (pedestal) subtracted during acquisition. There is a secondary pre-frame dark that can be applied which improves the counting quality. The detector is divided into 2 halves and a series of rows. Here is a quick diagram:
11111 | 11111
22222 | 22222
33333 | 33333
44444 | 44444

A row dark is calculated as the mean (or median) of each row on each side of the split in the center. Here is python code:
```python
# Determine the mean of each row for each side (detector is split down the middle)
raws_avg0 = np.mean(frame[:,:],axis=1) # might want to use median
raws_avg1 = np.mean(frame[:,:],axis=1)
            
# The row-dark is the mean of each row
dark[:,:288] = raws_avg0[:,None]
dark[:,288:] = raws_avg1[:,None]
            
# Divide out the row-dark and multiply by the data set's mean
# i.e. ****Statistics for calculating electron thresholds****
#      optimized mean: 19.477028281405794
f1['frames'][ii, :, :] = optimized_mean * frame / dark
```
This should be calculated and applied to each frame separately.

**Comment by psavery** [comment]
Hi @ercius. For the example above, the `raw_avg0` and `raw_avg1` appear to be identical. Is that supposed to be the case?

**Comment by ercius** [comment]
Good question. That was not intended. I mostly meant to label rows with their row number rather than putting a value in that row. A better labeling would be (L = left and R = right)
1L 1L 1L 1L 1L | 1R 1R 1R 1R 1R
etc.

And a better labeling of the possible pixel values is:
20 20 20 19 20 | 21 20 20 21 21
etc.

1L's mean is 24.75 and 1R's mean is 26.5. So the row dark is
24.75 24.75 24.75 24.75 24.75 | 26.5 26.5 26.5 26.5 26.5 
etc.

**Comment by psavery** [comment]
Thanks @ercius! However, I meant the code example actually. It appears that `raws_avg0` and `raws_avg1` are both equal to `np.mean(frame[:,:],axis=1)`.

**Comment by ercius** [comment]
That is not right at all. Im not sure how that made it through. Im checking my test code now and will update with the actual code. I can send you a full notebook once I know it runs correctly. Sorry about that!

**Comment by psavery** [comment]
@ercius Sounds good, thank you!

**Comment by ercius** [comment]
I ran through my code again to verify the code below. Ill send you the full notebook as well. But it should be:
```python
raws_avg0 = np.mean(frame[:, 0:288],axis=1)
raws_avg1 = np.mean(frame[:, 288:],axis=1)

# The row-dark is the mean of each row
dark[:, :288] = raws_avg0[:, None]
dark[:, 288:] = raws_avg1[:, None]

frame_processed = 20.0 * frame / dark
```

I also tried using the row `median` but the results were much worse. I think I took care of the datatypes. How hard would it be to add an option for that? Mean works for my test data set, but less sparse data might not work as well.
