### ISSUE TITLE
bin_scans does not work when SparseArray num_frames_per_scan > 1

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#261]
The logic in `SparseArray.bin_scans` does not work if `num_frames_per_scan` is > 1.

**Comment by psavery** [comment]
Hmm, so I do have a test running for `bin_scans` with `num_frames_per_scan > 1`. That is [here](https://github.com/OpenChemistry/stempy/blob/e1fa9940d021827497b418848aa24f742654ec66/tests/test_sparse_array.py#L453-L474).

Maybe that test is incorrect, or it doesn't cover the case you are running into?

**Comment by psavery** [comment]
Oh, nevermind, that one has just one frame per scan before binning. I'll try to come up with another example...

**Comment by psavery** [comment]
@ercius So, I found an exception that was occurring and I am able to fix it. Now I just need to make sure I come up with a good test case to ensure we are getting the correct result.
