### ISSUE TITLE
Add function to return fully dense ndarray

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#265]
Can we add a function to `SparseArray` to return the data as a normal fully dense array? This has been requested by a user to help with compatibility with some `py4dstem` functions. Of course, the user needs enough RAM to hold the full array. I guess `numpy` will give an out of memory error if they dont.

I think the operation would something like:
```python
def get_dense_array(self):
    self.allow_full_expand = True
    return self[:]
```

**Comment by psavery** [comment]
@ercius Sounds good. I added a `to_dense()` function in https://github.com/OpenChemistry/stempy/pull/266
