### ISSUE TITLE
Implement reader that allows reading specific frames

### ISSUE THREAD

**Issue by cjh1** [OpenChemistry/stempy#279]
The idea would be to have a version on the `SectorStreamMultiPassThreadedReader` that would allow the user to read just a set of frames. This could be implemented by first called [readHeaders](https://github.com/OpenChemistry/stempy/blob/master/stempy/reader.h#L530) to create the scan map. The API would then allow the user to specify a range of frames that they want to read at a give scan position. To implement this method we will need to refactor [processFrame](https://github.com/OpenChemistry/stempy/blob/master/stempy/reader.h#L549) so that we have a way of read just a set of frames from the map. The idea is the Python API would look something like this:

```python
import stempy.io as stio
reader = stio.reader(iFiles,stio.FileVersion.VERSION5, backend="multi-pass-partial") 
frames = reader.read_frames(scan_position, frame_slice)
```

Note: The first time `read_frames` is calling it would call `readHeader`, subsequent call can just reused the scan map. The reading of the frames can be done in a threadpool or just on a single thread, the idea is that it should be a subset.

**Comment by ercius** [comment]
Does the reader object contain any information about the scan? E.g. does `reader.scan_shape` provide the number of frames?

**Comment by cjh1** [comment]
> Does the reader object contain any information about the scan? E.g. does `reader.scan_shape` provide the number of frames?

No, that information is in the header, so you have to read a block.

**Comment by cjh1** [comment]
@ercius When the user specifies which frames they are interesting in would they uses the frameNumber as found in the header or the index ( as in 0, would be the first frame at the position, regardless of the frameNumer ).

**Comment by psavery** [comment]
> @ercius When the user specifies which frames they are interesting in would they uses the frameNumber as found in the header or the index ( as in 0, would be the first frame at the position, regardless of the frameNumber ).

@ercius FYI: the example I'm working with from `2022.01.13` has frame numbers like `1490148420` (each frame has its own unique number, and they all appear to be 10 digits).

**Comment by ercius** [comment]
Those ten digit frame numbers will not be useful to a user. I think those
are global frame numbers from the camera only useful for stitching sectors
into frames.

**Comment by psavery** [comment]
@ercius Just double-checking something: will the returned frames be electron counted, or raw frames?

**Comment by ercius** [comment]
Just raw frames.
