### ISSUE TITLE
BigMPI causes Cereal error

### ISSUE THREAD

**Issue by swelborn** [OpenChemistry/stempy#292]
This error occurs with what seems to be random times. 

```bash
RuntimeError: Failed to read 836 bytes from input stream! Read 132
```

I ran the following command on the distiller jobs folder:

```bash
grep -rl --include="*.out" 'RuntimeError: Failed to read' /global/cfs/cdirs/ncemhub/distiller/jobs/ > ~/RuntimeError_jobs.txt
```

This is the output:
<details>

<summary>RuntimeError_jobs.txt</summary>

/global/cfs/cdirs/ncemhub/distiller/jobs/6187/slurm-13083213.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6388/slurm-13200700.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6173/slurm-13056663.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6133/slurm-11488771.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6327/slurm-13170411.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6254/slurm-13125660.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6448/slurm-13222002.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6455/slurm-13223008.out
/global/cfs/cdirs/ncemhub/distiller/jobs/5387/slurm-2674179.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6375/slurm-13194823.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6240/slurm-13122082.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6200/slurm-13094426.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6196/slurm-13085878.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6500/slurm-13238649.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6496/slurm-13238069.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6182/slurm-13082172.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6142/slurm-11525534.out
/global/cfs/cdirs/ncemhub/distiller/jobs/5388/slurm-2674240.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6241/slurm-13122090.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6383/slurm-13200236.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6216/slurm-13102514.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6263/slurm-13131655.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6523/slurm-13249006.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6443/slurm-13221418.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6217/slurm-13102682.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6458/slurm-13223506.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6104/slurm-11374917.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6338/slurm-13173436.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6385/slurm-13200256.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6451/slurm-13222779.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6265/slurm-13132023.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6510/slurm-13244959.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6371/slurm-13194133.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6211/slurm-13100428.out
/global/cfs/cdirs/ncemhub/distiller/jobs/5778/slurm-9979500.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6492/slurm-13237978.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6266/slurm-13132470.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6273/slurm-13134617.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6511/slurm-13245297.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6467/slurm-13227523.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6193/slurm-13085114.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6274/slurm-13134879.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6380/slurm-13198898.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6260/slurm-13131163.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6140/slurm-11505433.out
/global/cfs/cdirs/ncemhub/distiller/jobs/5386/slurm-2674178.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6381/slurm-13199812.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6440/slurm-13221043.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6309/slurm-13149410.out
/global/cfs/cdirs/ncemhub/distiller/jobs/5993/slurm-10302723.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6477/slurm-13235007.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6397/slurm-13203355.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6222/slurm-13105884.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6416/slurm-13215291.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6284/slurm-13139168.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6390/slurm-13201590.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6223/slurm-13112011.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6318/slurm-13168261.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6304/slurm-13145999.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6125/slurm-11483834.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6319/slurm-13168382.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6465/slurm-13226959.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6330/slurm-13170730.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6472/slurm-13231092.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6367/slurm-13186465.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6426/slurm-13216443.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6313/slurm-13167623.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6174/slurm-13057687.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6412/slurm-13215260.out
/global/cfs/cdirs/ncemhub/distiller/jobs/5391/slurm-8657466.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6489/slurm-13237257.out
/global/cfs/cdirs/ncemhub/distiller/jobs/5604/slurm-8749061.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6175/slurm-13058742.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6135/slurm-11489179.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6460/slurm-13224797.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6234/slurm-13120176.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6475/slurm-13234353.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6249/slurm-13123293.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6362/slurm-13178156.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6136/slurm-11489183.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6461/slurm-13226449.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6509/slurm-13244957.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6436/slurm-13220101.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6137/slurm-11491438.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6283/slurm-13138673.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6199/slurm-13086943.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6258/slurm-13126151.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6364/slurm-13178439.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6324/slurm-13170107.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6204/slurm-13097554.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6350/slurm-13174372.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6292/slurm-13144031.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6486/slurm-13236466.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6446/slurm-13221886.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6172/slurm-13056078.out
/global/cfs/cdirs/ncemhub/distiller/jobs/6132/slurm-11488765.out

</details>

And the earliest job that does this 5386 is on **May 11**:
```
.rwxr-----  475 dstlr ncemhub 11 May 11:29  bbcp.sh
.rw-rw---- 1.7k dstlr ncemhub 11 May 11:29  count-5386.sh
.rw-rw----  39k dstlr ncemhub 11 May 11:59  slurm-2674178.out
```

Here is the relevant part of the job output:

<details>
<summary>slurm-2674178.out</summary>

```bash
****Statistics for calculating electron thresholds****
number of samples:1200
min sample:11
max sample:969
mean:20.5008
variance:22.5582
std dev:4.74955
number of bins:958
x-ray threshold n sigma:175
background threshold n sigma:4
optimized mean:20.4486
optimized std dev:1.77675
background threshold:27.5556
xray threshold:851.672
electron_count_cori.py
Using files in /var/opt/cray/dws/mounts/batch/2674178_striped_scratch/5386
scan name = data_scan0000000244_*.data
start counting #244
Traceback (most recent call last):
  File "/global/cfs/cdirs/ncemhub/distiller/scripts/electron_count_cori.py", line 64, in <module>
    electron_counted_data = stim.electron_count(sReader, dark0, gain=gain0,number_of_samples=1200,verbose=True,threshold_num_blocks=20,xray_threshold_n_sigma=175, background_threshold_n_sigma=th)
  File "/usr/local/lib/python3.7/site-packages/stempy/image/__init__.py", line 262, in electron_count
    data = _image.electron_count(reader, options)
RuntimeError: Failed to read 836 bytes from input stream! Read 132
electron_count_cori.py
Using files in /var/opt/cray/dws/mounts/batch/2674178_striped_scratch/5386
scan name = data_scan0000000244_*.data
start counting #244
electron_count_cori.py
Using files in /var/opt/cray/dws/mounts/batch/2674178_striped_scratch/5386
scan name = data_scan0000000244_*.data
start counting #244
electron_count_cori.py
Using files in /var/opt/cray/dws/mounts/batch/2674178_striped_scratch/5386
scan name = data_scan0000000244_*.data
start counting #244
electron_count_cori.py
Using files in /var/opt/cray/dws/mounts/batch/2674178_striped_scratch/5386
scan name = data_scan0000000244_*.data
start counting #244
electron_count_cori.py
Using files in /var/opt/cray/dws/mounts/batch/2674178_striped_scratch/5386
scan name = data_scan0000000244_*.data
start counting #244
electron_count_cori.py
Using files in /var/opt/cray/dws/mounts/batch/2674178_striped_scratch/5386
scan name = data_scan0000000244_*.data
start counting #244
electron_count_cori.py
Using files in /var/opt/cray/dws/mounts/batch/2674178_striped_scratch/5386
scan name = data_scan0000000244_*.data
start counting #244
electron_count_cori.py
Using files in /var/opt/cray/dws/mounts/batch/2674178_striped_scratch/5386
scan name = data_scan0000000244_*.data
start counting #244
slurmstepd: error: *** STEP 2674178.1 ON nid00736 CANCELLED AT 2023-05-11T11:59:34 DUE TO TIME LIMIT ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** REASON: burst_buffer/datawarp: Stage-out in progress ***
srun: got SIGCONT
srun: forcing job termination
```
</details>

[BigMPI](https://github.com/OpenChemistry/stempy/pull/285) seems to be the cause -- it was merged **May 10**...

We noticed this in a recent streaming session, where stempy isn't called through python. The error when called directly in a binary is:

```bash
terminate called after throwing an instance of 'cereal::Exception'
  what():  Failed to read 8 bytes from input stream! Read 4
```

This is ocurring after counting is finished, likely somewhere in [gatherEvents](https://github.com/OpenChemistry/stempy/blob/0bb5eaafbbbb7485818153f9e2997d95a122db91/stempy/electron.cpp#L796).

I think what is happening is that the MPI sends/receives are getting mixed up here:

Sends:
```c++
  MPI_Send(&size, 1, MPI_UINT64_T, 0, 0, MPI_COMM_WORLD);

  // Now send the data using BigMPI
  MPIX_Send_x(eventsContiguousStream.GetData(),
              eventsContiguousStream.GetSize(), 
```

Receives:
```c++
  size_t msgSize;
  MPI_Recv(&msgSize, 1, MPI_UINT64_T, MPI_ANY_SOURCE, 0, MPI_COMM_WORLD,
           MPI_STATUS_IGNORE);

  // Resize our buffer
  recvBuffer.resize(msgSize);

  // Now receive the data using BigMPI
  MPIX_Recv_x(recvBuffer.data(), recvBuffer.size(), MPI_BYTE, MPI_ANY_SOURCE, 0,
              MPI_COMM_WORLD, MPI_STATUS_IGNORE);

```

But I could be wrong, I don't know MPI. 

Let me know what you think @psavery.

**Comment by psavery** [comment]
I am not sure on first glance. @cjh1 primarily worked on this code, so I am not that familiar with it. But I can take a closer look if needed.

**Comment by swelborn** [comment]
I think this might work:
https://github.com/swelborn/stempy/commit/3193e79b5c371423516a667f42650633e3b15953

I will test it sometime next week.
