### ISSUE TITLE
No wheel files for Apple Silicon computers

### ISSUE THREAD

**Issue by aducharme** [OpenChemistry/stempy#296]
The Mac-oriented .whl files in Pypi for all versions save 0.0.1 use the tag -macosx_10_9_x86_64, which works for Macs with Intel chips, but not for M1, M2, and other Apple Silicon processors. These want tags that end in _arm64 or _universal2, which are not available for stempy. This causes pip installations on Apple Silicon computers to only install version 0.0.1, as it is built from a .tar.gz, not from a .whl.

**Comment by psavery** [comment]
@aducharme one of the challenges is that we are using GitHub Actions to generate the wheels, and GitHub Actions unfortunately does not have M1 runners yet. Hopefully, they will have M1 runners in the next few months (that is being tracked [here](https://github.com/github/roadmap/issues/528)), which will make generating these wheels a lot easier. We might be able to cross-compile and generate a universal wheel, but I've ran into time-consuming issues with that in other projects (and I probably shouldn't try it unless we really need it).

In the meantime, we can build M1 wheels manually on a local machine and push them to PyPI, but probably not for every tag. Which version of Python are you using? I can try to build a wheel for it and upload it to PyPI.

**Comment by aducharme** [comment]
Okay, understood. I'm using Python 3.10, but for a non-personalized solution, what about releasing another .tar.gz, or putting stempy on conda-forge?

**Comment by psavery** [comment]
We could put up another `.tar.gz`, but the user would need to have the C++ dependencies set up properly to compile it. You can still do that currently with the git repo on Mac as follows:
```bash
# Install system libraries
brew install eigen hdf5@1.10 ninja
brew link hdf5@1.10

# Clone the repo
git clone --recursive https://github.com/openchemistry/stempy

# Compile and install
pip install ./stempy
```

I don't necessarily want to recommend users to modify their system libraries, though. For instance, this will overwrite any previously installed HDF5 versions. You can try this, though, if you'd like. This should install stempy correctly.

Setting stempy up on conda-forge would probably be a good idea as it makes the C++ dependencies easier to work with. I believe it is easier to cross-compile for M1 chips on conda-forge as well. However, it would require a little work and we would need funding to do so.

Waiting until the M1 runners become available for GitHub actions is another option.

**Comment by psavery** [comment]
@ercius The C++ libraries are also used for a few other things, including creating STEM images and most of the file readers. There are several functions that don't use C++, and the SparseArray class doesn't use C++ either, so we could potentially separate those out, but we'd have to do some code reorganization to do so. 

@aducharme I created a wheel for Python3.10 on M1, and here it is:
[stempy-3.3.5-cp310-cp310-macosx_13_0_arm64.whl.zip](https://github.com/OpenChemistry/stempy/files/12428336/stempy-3.3.5-cp310-cp310-macosx_13_0_arm64.whl.zip)

You can download it and unzip it, and then `pip install ./stempy-3.3.5-cp310-cp310-macosx_13_0_arm64.whl` to install it.

I don't have permission to upload it to PyPI yet (@cjh1, can you give me permission when you get a chance?)

Once the M1 runners come out for GitHub actions, these wheels will get created automatically.

**Comment by cjh1** [comment]
@psavery Looks like we might be able to cross-compile ( I am trying it out ). It looks like m1 runners have arrived, but not sure they are available unless you pay ...

**Comment by psavery** [comment]
@cjh1 Let me know how it goes!
