### ISSUE TITLE
Github and pypi tags out of sync?

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#297]
The newest tag on Github is 3.3.4 and on pypi its 3.3.5. Are we out of sync?

**Comment by psavery** [comment]
It looks like @cjh1 has been manually creating releases. You can see that 3.3.5 is the latest tag [here](https://github.com/OpenChemistry/stempy/tags), but there's no release for it [here](https://github.com/OpenChemistry/stempy/releases).

**Comment by ercius** [comment]
I did not think to look at the tags instead of the releases. 3.3.5 only includes some fix for MPI counting. Thanks!

**Comment by cjh1** [comment]
I am back! I created 3.3.5 and cut a new release (3.3.6) ...
