### ISSUE TITLE
How to build stempy in Windows11 operating system?

### ISSUE THREAD

**Issue by PhysXu** [OpenChemistry/stempy#316]
Hi,
How can I build stempy in the win-11 operating system?
I have tried using anaconda to build stempy in a virtual Environment:
```
git clone https://github.com/OpenChemistry/stempy.git
cd stempy
pip install .
```

But got the following error:
![image](https://github.com/OpenChemistry/stempy/assets/35793078/6b8c1885-57ac-4cb4-9522-6322658a6a0e)

Is there anything wrong in the above method?
**The python-version is 3.10 and cmake is 3.30**

**Comment by cjh1** [comment]
Hi @PhysXu, stempy does build on windows, we have binary wheel that you should be able to pip install using `pip install stempy`. [This](https://github.com/OpenChemistry/stempy/blob/master/.github/workflows/build_wheels.yml) is the GitHub actions workflow that builds the wheels.

**Comment by PhysXu** [comment]
> Hi @PhysXu, stempy does build on windows, we have binary wheel that you should be able to pip install using `pip install stempy`. [This](https://github.com/OpenChemistry/stempy/blob/master/.github/workflows/build_wheels.yml) is the GitHub actions workflow that builds the wheels.

Hi, @cjh1 ,
Succeed!
![image](https://github.com/OpenChemistry/stempy/assets/35793078/c594b7d4-4389-443d-a6d7-ab1a72c3e96a)

Thanks very much for your reply.
