### ISSUE TITLE
non square stem scans

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#74]
stempy does not work with 4D Camera data which is not square. Please check the data in .../ncemhub/4Dcamera/2019.07.11/data_scan73*.data

This data should be 65 x 512, but stempy shows weird output:
![image](https://user-images.githubusercontent.com/15657108/61151147-1114b780-a49a-11e9-8a0f-65799e7fa7bc.png)

Manually analyzing the data gives this output:
![image](https://user-images.githubusercontent.com/15657108/61151161-1d991000-a49a-11e9-81f9-184dd61f83af.png)

I can provide a jupyter notebook to recreate these images.

**Comment by cjh1** [comment]
@ercius If you could send me the notebook, that would be great, thanks.

**Comment by ercius** [comment]
This is fixed in the stempy kernel on Cori, but it is not fixed for the stem.tomviz.org server. Can you update that server to use the more recent version of stempy?

**Comment by cjh1** [comment]
@ercius Certainly, will do that today.

**Comment by cjh1** [comment]
@ercius The stem.tomviz.org worker is now updated.

**Comment by ercius** [comment]
works! Thanks!
