### ISSUE TITLE
electron_count improvements

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#76]
1. The value for the background_threshold_n_sigma and x_ray_ variables in:
```stempy.image.electron_count```
only accept integers. This should accept float values as well. 

2. Please provide options for verbose output. It would be very nice to know the parameters of the gaussian fit used to determine the sigma value. center, sigma, and maximum.

3. width/height and frame_width/frame_height should be determined from the reader which loaded the data.

**Comment by cjh1** [comment]
For 3. we do determine the width and height from the reader in the `electron_count(...)`, those parameters are optional. I assume we are talking about `create_stem_images_sparse(...)` in which case we require those parameters as we are passing in the sparse dataset with doesn't have this information. We can look at attaching it in some way to make those parameters options.

**Comment by ercius** [comment]
Yes. That was what I wanted. The sparse data output should retain the
metadata.

**Comment by cjh1** [comment]
Note for future implementer. I think for 3. we should change the return type of [electronCount](https://github.com/OpenChemistry/stempy/blob/master/stempy/electron.h#L9) to be a small structure containing the `vector`, we can then add the scan and frame dimensions to the structure. We will then need add the appropriate buffer protocol definition so the the new structure can still be used as a numpy array ....

**Comment by cjh1** [comment]
@ercius I have just updated the images on cori that resolves 1 and 3. Note that `electron_count(...)` now returns an object that has a property called `data` which is the numpy array, as well as properties for the various dimensions. This object can be passed directly to `create_stem_images_sparse(...)`, removing the need to pass in all the dimensions.

**Comment by ercius** [comment]
@cjh1 That is great! It makes the processing much easier. Thanks a lot.
