### ISSUE TITLE
create_stem_image_sparse

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#77]
```create_stem_image_sparse``` does not seem to be working as expected. Half of the image is not the correct intensity compared to a non-counted STEM image.
![image](https://user-images.githubusercontent.com/15657108/61254577-cf923f80-a719-11e9-99c9-38836ec2cbe8.png)

Im not sure if this is due to counting or the STEM image creation.

I copied the notebook to ...../ncemhub/cjh1 on Cori.

**Comment by cjh1** [comment]
This is an odd one, there seems to be values in the bottom half of the image, just very low intensity and clearly wrong!

**Comment by ercius** [comment]
Very strange. I think this only happens for the sparse version. I'm pretty
sure the other version which operates on the full data works as expected.

**Comment by ercius** [comment]
Maybe this is related to the initial issue, but this function is also slower than I expect. I wrote a quick version in python and it took about 7 seconds to calculate the STEM images. This takes about a minute for the same data. Something to look into.

**Comment by cjh1** [comment]
@ercius Thank, that is another good data point. Definitely shouldn't that slow.

**Comment by cjh1** [comment]
@ercius I finally got the bottom of this, and unsigned integer wrap, can way it should be fixed by #80 and I have already push images to cori for you to test.

**Comment by ercius** [comment]
Nice. It works great. Thanks!
