### ISSUE TITLE
reader seg faults

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#79]
There have been two times when seg faults happen during raw data reading and analysis. We should avoid seg faults for bad data and user errors.

1. When a 4D Camera file is not written fully. Examples of this are in ncemhub/2019.07.16/. Ive had to rename several files to get stempy to analyze data. Bad files might exist for various reasons such as canceling the scan or HDD filling up. Currently, bad files cause the kernel to seg fault. It would be good to have a way to gracefully catch this error and not lose all data that was processed already.

2. I named a processed file `data_scan156_20frames.npy` and then asked stempy to read all data files named `data_scan156*`. This also caused a seg fault in the kernel. This might not be an easy error to handle since the error exists between keyboard and chair (PEBKAC), but it would be good to catch errors like this and not cause a core dump.

**Comment by cjh1** [comment]
Absolutely! We should look guarding against these two.

**Comment by cjh1** [comment]
For 1.Was the a particular scan to try with?

**Comment by ercius** [comment]
For 1 try this:
```python
from pathlib import Path
from stempy import io, image

# Paths to ncemhub and data root directory
ncemhub = Path('/global/project/projectdirs/ncemhub/')
dPath = ncemhub / Path('4Dcamera/2019.07.16/')
imName = 'data_scan197_dst0*.data' # limit files to one receiver to fail quicker
imFiles = [str(f) for f in dPath.glob(imName)]
reader2 = io.reader(imFiles, version=io.FileVersion.VERSION3)
avgI = image.calculate_average(reader2)
```

**Comment by cjh1** [comment]
@ercius I tried to recreate 1. I am seeing a EOF error rather than a segfault, which is kinda what I would expect. May be you could point me at the notebook?

**Comment by ercius** [comment]
@cjh1 Look like this can not be reproduced now. I just tested this and also see a EOF error raised:
```ValueError: Unexpected EOF while processing stream.```

Let's call it fixed! Nice work :)

**Comment by cjh1** [comment]
OK, let me know if it crops up again :smile:

**Comment by cjh1** [comment]
Calling this fixed
