### ISSUE TITLE
question: using multiple nodes

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#86]
I have been using stempy from a notebook through Jupyter on NERSC (runs on login nodes). Is there a way to run this using multiple batch nodes? Im not expecting to use a notebook. An example of a py file and job script for electron counting a data set would be very useful.

**Comment by ercius** [comment]
Actually, the examples directory has some scripts. But Im not sure how to use one of these with a job submission script.

**Comment by cjh1** [comment]
@ercius We can provide an example for creating a STEM image on multiple nodes, as this is a process that can be easily partition cross nodes. However, the current electron counting algorithm requires more knowledge across the entire set data, for example when calculating the thresholds. So some work would be needed to either calculate these on each node or communicate them from rank zero. I can take a look at doing this, we held off as we thought the electron counting would probably end up happening in the detector hardware.

**Comment by ercius** [comment]
Good point regarding the counting in the hardware. If it looks like a lot
of work then we can ignore this request. However, it might be some time
before we push this to hardware, so it could still be with implementing.

**Comment by cjh1** [comment]
@ercius I have added a simple example CLI script that will generate stem images across multiple nodes. It is basically the code we are using to do the interactive pipelines on stem.tomviz.org. Here is an example invocation ( this would be in your batch submission script ).

```bash
srun -N $SLURM_JOB_NUM_NODES shifter --image=openchemistry/stempy  -- python3 /source/stempy/examples/create_stem_mpi.py --center 274,308 --inner-radii 0 --outer-radii 50 /global/project/projectdirs/ncemhub/4Dcamera/2019.07.11/data_scan73*.data
```
This should work as is, although cori is having IO issues so performance may ( and does ) vary!

You can of course use stem.tomviz.org using an interactive allocation to do the same thing. Is there particular use case for running these operations in batch?

We will at the electron counting code, to see if we can easily get it working across nodes.

**Comment by cjh1** [comment]
@ercius We have added another CLI script that will do the electron counting across multiple nodes. Here is a example submission script: 
```
#!/bin/bash
#SBATCH -q regular
#SBATCH -C haswell
#SBATCH -t 00:30:00
#SBATCH --cpus-per-task=16
#SBATCH --constraint=haswell

export OMP_PROC_BIND=true
export OMP_PLACES=threads
export OMP_NUM_THREADS=8

echo "Number of node: ${SLURM_JOB_NUM_NODES}"
echo "Number of threads: ${OMP_NUM_THREADS}"
echo "Tasks per node: ${SLURM_TASKS_PER_NODE}"

srun shifter --image=openchemistry/stempy:latest  -- python3 /source/stempy/examples/electron_mpi.py $SCRATCH/scan_45/data_scan45_dst* -d $SCRATCH/scan_62/data_scan62_dst0_file0.data 

```
You would submit this with the following invocation:

```
sbatch -N 8 --ntasks-per-node=4  electron.sh
```
This will write out an HDF5 file (`electron_counted_data.h5`) containing the electron counts. The structure is described [here.](https://github.com/OpenChemistry/stempy/blob/master/docs/StempyH5Format.md)
