### ISSUE TITLE
electron count number_of_samples

### ISSUE THREAD

**Issue by ercius** [OpenChemistry/stempy#91]
The number_of_samples keyword for image.electron_count() does not affect the verbose output. The calculation takes longer, but the values output are identical. 

Not sure if this is an issue with output or the actual calculation.

Here is output with 4 samples:
****Statistics for calculating electron thresholds****
number of samples: 4
min sample: -10
max sample: 180
mean: 0.37965675636574076
variance: 5.3071482510286785
std dev: 2.303724864437739
number of bins: 64
x-ray threshold n sigma: 10.0
background threshold n sigma: 4.0
background threshold: 8.20291666947256
xray threshold: 23.416905400743133

Here is the output with 40 samples:
****Statistics for calculating electron thresholds****
number of samples: 40
min sample: -10
max sample: 180
mean: 0.37965675636574076
variance: 5.3071445541374604
std dev: 2.3037240620650428
number of bins: 64
x-ray threshold n sigma: 10.0
background threshold n sigma: 4.0
background threshold: 8.202780824561396
xray threshold: 23.41689737701617

**Comment by cjh1** [comment]
@ercius I tried this locally and it seems to work, as in the mean etc changes. Could you point me to the dataset you are using or even better the notebook?

**Comment by ercius** [comment]
I think this is fixed. Probably an issue with updating (pip install -U) the python code locally.
